services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mp-frame-client
    ports:
      - "1337:3000"
    volumes:
      - ./client:/client
      - ./shared:/shared
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mp-frame-server
    ports:
      - "1338:3000"
    volumes:
      - ./server:/server
      - ./shared:/shared